#!/bin/bash

echo "Stop session-manager service"

systemctl disable session-manager.service
systemctl stop session-manager.service
systemctl daemon-reload

echo "Clear poetry-env"
rm -rf $(poetry env info --path)

